const cardlist = [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'img/words/cry.jpg',
      audioSrc: 'audio/cry.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'img/words/dance.jpg',
      audioSrc: 'audio/dance.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'img/words/dive.jpg',
      audioSrc: 'audio/dive.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'img/words/draw.jpg',
      audioSrc: 'audio/draw.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'img/words/fish.jpg',
      audioSrc: 'audio/fish.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'img/words/fly.jpg',
      audioSrc: 'audio/fly.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'img/words/hug.jpg',
      audioSrc: 'audio/hug.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'img/words/jump.jpg',
      audioSrc: 'audio/jump.mp3',
      category: 'Action (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'open',
      translation: 'открывать',
      image: 'img/words/open.jpg',
      audioSrc: 'audio/open.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'img/words/play.jpg',
      audioSrc: 'audio/play.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'img/words/point.jpg',
      audioSrc: 'audio/point.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'img/words/ride.jpg',
      audioSrc: 'audio/ride.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'img/words/run.jpg',
      audioSrc: 'audio/run.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'img/words/sing.jpg',
      audioSrc: 'audio/sing.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'img/words/skip.jpg',
      audioSrc: 'audio/skip.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'img/words/swim.jpg',
      audioSrc: 'audio/swim.mp3',
      category: 'Action (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'cat',
      translation: 'кот',
      image: 'img/words/cat.jpg',
      audioSrc: 'audio/cat.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'img/words/chick.jpg',
      audioSrc: 'audio/chick.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'img/words/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'img/words/dog.jpg',
      audioSrc: 'audio/dog.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'img/words/horse.jpg',
      audioSrc: 'audio/horse.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'img/words/pig.jpg',
      audioSrc: 'audio/pig.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'img/words/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'img/words/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
      category: 'Animal (set A)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'bird',
      translation: 'птица',
      image: 'img/words/bird.jpg',
      audioSrc: 'audio/bird.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'img/words/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'img/words/frog.jpg',
      audioSrc: 'audio/frog.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'giraffe',
      translation: 'жираф',
      image: 'img/words/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'img/words/lion.jpg',
      audioSrc: 'audio/lion.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'img/words/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'img/words/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'img/words/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
      category: 'Animal (set B)',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'img/words/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'img/words/pants.jpg',
      audioSrc: 'audio/pants.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'img/words/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'img/words/dress.jpg',
      audioSrc: 'audio/dress.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'img/words/boot.jpg',
      audioSrc: 'audio/boot.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'img/words/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'img/words/coat.jpg',
      audioSrc: 'audio/coat.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'img/words/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
      category: 'Clothes',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'sad',
      translation: 'грустный',
      image: 'img/words/sad.jpg',
      audioSrc: 'audio/sad.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'img/words/angry.jpg',
      audioSrc: 'audio/angry.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'img/words/happy.jpg',
      audioSrc: 'audio/happy.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'img/words/tired.jpg',
      audioSrc: 'audio/tired.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'img/words/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'img/words/scared.jpg',
      audioSrc: 'audio/scared.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'img/words/smile.jpg',
      audioSrc: 'audio/smile.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'img/words/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
      category: 'Emotions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'engineer',
      translation: 'инженер',
      image: 'img/words/engineer.jpg',
      audioSrc: 'audio/engineer.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'writer',
      translation: 'писатель',
      image: 'img/words/writer.jpg',
      audioSrc: 'audio/writer.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'actor',
      translation: 'актер',
      image: 'img/words/actor.jpg',
      audioSrc: 'audio/actor.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'designer',
      translation: 'дизайнер',
      image: 'img/words/designer.jpg',
      audioSrc: 'audio/designer.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'doctor',
      translation: 'врач',
      image: 'img/words/doctor.jpg',
      audioSrc: 'audio/doctor.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'lawyer',
      translation: 'юрист',
      image: 'img/words/lawyer.jpg',
      audioSrc: 'audio/lawyer.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'driver',
      translation: 'водитель',
      image: 'img/words/driver.jpg',
      audioSrc: 'audio/driver.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'builder',
      translation: 'строитель',
      image: 'img/words/builder.jpg',
      audioSrc: 'audio/builder.mp3',
      category: 'Professions',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'yellow',
      translation: 'желтый',
      image: 'img/words/yellow.jpg',
      audioSrc: 'audio/yellow.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'green',
      translation: 'зеленый',
      image: 'img/words/green.jpg',
      audioSrc: 'audio/green.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'blue',
      translation: 'синий',
      image: 'img/words/blue.jpg',
      audioSrc: 'audio/blue.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'gray',
      translation: 'серый',
      image: 'img/words/gray.jpg',
      audioSrc: 'audio/gray.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'red',
      translation: 'красный',
      image: 'img/words/red.jpg',
      audioSrc: 'audio/red.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'orange',
      translation: 'оранжевый',
      image: 'img/words/orange.jpg',
      audioSrc: 'audio/orange.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'pink',
      translation: 'розовый',
      image: 'img/words/pink.jpg',
      audioSrc: 'audio/pink.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    },
    {
      word: 'black',
      translation: 'черный',
      image: 'img/words/black.jpg',
      audioSrc: 'audio/black.mp3',
      category: 'Colors',
      train_click: 0,
      play_true: 0,
      play_false: 0,
      percentage_incorrect: 0,
    }
];



